### ISSUE TITLE
Packit and RHEL in GitLab

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/research#182]
The goal of this initiative is to design a CI management system for RHEL dist-git repositories saved at gitlab.com/redhat.

## User stories

* As a contributor, when I open a merge request, I want to see the results of the CI systems needed to run on my change so I can improve my contribution.
* As a package maintainer, I want to be able to specify CI systems I want my package to use so the combination of CI runs makes for 
* As a CI maintainer/developer, I want to have a REST API that I can pull my work from and push results to.
* As a CI maintainer/developer, Pipeline administrator, I want to see the state of tasks in a queue so I can realise problems with a particular CI system.

## Architecture

The basic idea is that there will be two main parts of the architecture:
* `MR CI`
  * Responsible for reacting to user events.
  * Responsible for breaking down the CI workflow into single tasks (done by `Task Mediator`).
  * Responsible for showing the results to our users.
* `Task Mediator`
  * Accepts tasks by `MR CI`.
  * Allows CI systems to pull the tasks. (Pull-workflow. CI system implements the integration.)
  * Allows CI systems to push the task results.

## Implementation:
* Reuse as much as possible from the current code base or -- ideally -- improve -- the current service to support this use case as well. (We don't have bandwidth to support two very different use-cases so we need to come with an architecture that can be used for the current Packit as well.) Use this as a chance to improve the current service implementation..;)
* Learn from what we've done and what troubles we've met. Don't do the same faults again.

## Tasks:
* [x] Meet with the RHEL@GitLab people and get the requirements.
* [ ] Take a look at existing workflow engines if we can't (re)use anything.
* [ ] Research how configuration can be done. (The original idea is to have a single repository where all the packages will define the CI systems to run. Similar to how Fedora Zuul is configured for packages.)
* [ ] Design the MVP
* [ ] Plan and estimate the tasks for implementation.
